# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: 'install, run, test'
        shell: bash
        run: |
          npm ci
          npm run build
          npx playwright install
          npm run test
        continue-on-error: true
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            test-results
            !dist/**/*.md
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: save PR number
        if: always()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
