# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Screenshot Testing

on:
  push:
    branches: [main, action]
  pull_request:
    branches: [main, action]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: 'install, run, test'
        shell: bash
        run: |
          npm ci
          npm run build
          npx playwright install
          npm run test
        continue-on-error: true
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            test-results
            !dist/**/*.md
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: |
          cd e2e-example-example-test
          ls
      - name: upload diffs to imgur
        if: always()
        uses: pengpengzx/actions/packages/upload-images@main
        id: imgur
        with:
          path: e2e-example-example-test
          workspace: ${{ github.workspace }}
          os: linux
          token: ${{ secrets.TOKEN }}
      - name: prepare comment body
        id: comment-body
        uses: actions/github-script@v5
        with:
          script: |
            const imgArr = ${{steps.imgur.outputs.images}};
            console.log(imgArr)
            if (Array.isArray(imgArr) && imgArr.length) {
              str += `
                <strong>平台</strong>
                | Actual | Diff | Expected |
                |:------:|:----:|:--------:|
              `;
              imgArr.forEach(({ actual, diff, expected }) => {
                str += `
                  | ${actual.name} | ${diff.name} | ${expected.name} |
                  | ![${actual.name}](${actual.link}) | ![${diff.name}](${diff.link}) | ![${expected.name}](${expected.link}) |
                `;
              });
              str += '\n\n';
              await github.rest.issues.createComment({
                  owner: "pengpengzx",
                  repo: "next-demo",
                  issue_number: 1,
                  body: str
                });
            }
