name: Screenshot Test

on:
  push:
    branches: [ui-test, feat/SC_SAAS-5598]
  pull_request:
    branches: [ui-test, feat/SC_SAAS-5598]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./functions" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "14.x" # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run test
        run: |
          apt-get update
          apt-get install fontconfig
          fc-list
