name: 'PR Reporting'
on:
  workflow_dispatch:
    inputs:
      runId:
        description: run id
        required: true

  workflow_run:
    workflows: ['UI tests']
    types:
      - 'completed'

jobs:
  comment-on-pr:
    # if: github.event.workflow_run.event == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [ubuntu-20.04]
    runs-on: ubuntu-20.04
    steps:
      - name: download artifacts
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const fs = require('fs');
            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id || github.event.inputs.runId }},
            });

            const playwrightArtifacts artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "playwright-results-${{ matrix.os }}"
            })[0];

            const downloadPlaywright = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: reportArtifacts.id,
               archive_format: 'zip',
            });
            fs.writeFileSync('${{github.workspace}}/playwright-results-${{ matrix.os }}.zip', Buffer.from(downloadPlaywright.data));
      - name: unzip stuff
        run: |
          unzip playwright-results-${{ matrix.os }}.zip
      - name: ls on files
        run: ls
